version: '3'
services:
  legacy-challenge-resource-processor:
    image: legacy-challenge-resource-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    network_mode: "host"
